field: e3d484bd-fc08-4e00-aa53-3d47583daa9f # Gallery Images
fieldLayouts:
  d1d35c1a-5088-4380-a396-f851e3553a33:
    tabs:
      -
        elements:
          -
            fieldUid: a1686e3d-1865-445a-852d-25a24e433860 # Gallery Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  a1686e3d-1865-445a-852d-25a24e433860: # Gallery Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: galleryImage
    instructions: ''
    name: 'Gallery Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:bccbaeb1-4536-435a-8cf9-4fd3ffdf59e6' # Uploads
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:bccbaeb1-4536-435a-8cf9-4fd3ffdf59e6' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: gallery
name: Gallery
sortOrder: 1
