columnSuffix: null
contentColumnType: string
fieldGroup: af33e277-8e52-4332-aa0d-9efdbe5fdb0e # Common
handle: pageEntyImage
instructions: 'Image that will go on the top of the page and be shown when searching articles.'
name: 'Page Enty Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:bccbaeb1-4536-435a-8cf9-4fd3ffdf59e6' # Uploads
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:bccbaeb1-4536-435a-8cf9-4fd3ffdf59e6' # Uploads
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
