dateModified: 1646360809
email:
  fromEmail: takeacloserlookministries1@gmail.com
  fromName: takeacloserlookministries1@gmail.com
  replyToEmail: takeacloserlookministries1@gmail.com
  template: null
  transportSettings:
    password: Microsoft1!
    timeout: '10'
    username: takeacloserlookministries1@gmail.com
  transportType: craft\mail\transportadapters\Gmail
meta:
  __names__:
    0f6e04df-ce19-4a89-b89d-e879e822e087: cataldo # cataldo
    1e1c76bf-adb2-42c6-8c5a-b7a9e7f3590a: 'Full Caption' # Full Caption
    02a36630-55a8-4e27-bff9-baf27ef9366f: Blog # Blog
    3a37bd5e-2600-4ff2-ab18-fbaea082805f: 'Author Bio' # Author Bio
    5b9d684d-5da2-445d-bc48-51b9ae352a6c: 'Page Content' # Page Content
    6b7954cf-58df-4a94-ac7f-1064c8137e1d: Galleries # Galleries
    6ccefa7f-ee06-4420-8548-da5867487510: 'Public Schema' # Public Schema
    8ba2b35c-4f68-4570-b288-56f2e0dda92b: category # category
    42ecf3de-1855-4712-8a70-a5ffe8b5b546: Globals # Globals
    43b1aff8-18d4-4ba3-93ec-d0f2e3415d5b: Globals # Globals
    082c475d-689f-427b-90b2-a941e80f665b: Gallery # Gallery
    600f401e-826d-4a9b-a4ff-6003ca8d4055: 'Short Caption' # Short Caption
    7637aad2-967f-4c26-8220-284ff09a09ab: cataldo # cataldo
    7798dd4a-df02-4fb9-bd74-ba5b3861a3b2: Page # Page
    63286c93-ccf3-4610-a89f-1aeef4ff2dda: Default # Default
    978256b4-4917-4876-8f86-256ffdfe172e: Default # Default
    a79ad683-3a03-4fe2-920c-4b25c26bd7fc: Videos # Videos
    a1686e3d-1865-445a-852d-25a24e433860: 'Gallery Image' # Gallery Image
    af33e277-8e52-4332-aa0d-9efdbe5fdb0e: Common # Common
    bb4dae1a-23b5-400a-b7cb-ccf8279434d4: 'Author Image' # Author Image
    bccbaeb1-4536-435a-8cf9-4fd3ffdf59e6: Uploads # Uploads
    c3569781-d326-4dfa-8d53-ba57a0197882: Default # Default
    d20675ef-c5e0-4457-a05d-39531760cc5c: 'Page Enty Image' # Page Enty Image
    ddd8a27a-43c8-4331-b6ae-4b64ada36fac: 'Video Embed' # Video Embed
    e3d484bd-fc08-4e00-aa53-3d47583daa9f: 'Gallery Images' # Gallery Images
    e5aeeef1-b40f-4e0b-8f8e-e4b445b9b1a7: 'Author Name' # Author Name
    e5417985-058f-4465-9fca-c5cdf7815986: Category # Category
    ee00171d-429b-41c1-8eda-df7ecf4eb46e: Galleries # Galleries
plugins:
  comments:
    enabled: true
    licenseKey: HPUA3UW9PJORAAMHEU3JDFQH
    schemaVersion: 1.1.7
    settings:
      allowAnonymous: null
      allowAnonymousFlagging: null
      allowAnonymousVoting: null
      allowFlagging: true
      allowGuest: false
      allowGuestFlagging: false
      allowGuestVoting: false
      allowVoting: true
      autoCloseDays: ''
      closed: null
      defaultQueryStatus:
        - approved
      downvoteCommentLimit: 5
      enableGravatar: false
      enableSpamChecks: true
      flaggedCommentLimit: 5
      guestNotice: ''
      guestRequireEmailName: true
      guestShowEmailName: true
      hideVotingForThreshold: false
      indexSidebarGroup: true
      indexSidebarIndividualElements: false
      indexSidebarLimit: 25
      maxReplyDepth: null
      maxUserComments: null
      moderatorUserGroup: null
      notificationAdminEnabled: false
      notificationAuthorEnabled: true
      notificationFlaggedEnabled: false
      notificationModeratorApprovedEnabled: false
      notificationModeratorEnabled: false
      notificationReplyEnabled: true
      notificationSubscribeAuto: false
      notificationSubscribeCommentEnabled: false
      notificationSubscribeDefault: true
      notificationSubscribeEnabled: false
      outputDefaultCss: true
      outputDefaultJs: true
      permissions: null
      placeholderAvatar: null
      recaptchaEnabled: false
      recaptchaKey: null
      recaptchaSecret: null
      requireModeration: true
      securityBanned: null
      securityFlooding: null
      securityMatchExact: false
      securityMaxLength: null
      securityModeration: null
      securitySpamlist: null
      showAvatar: true
      showCustomFieldInstructions: false
      showCustomFieldNames: false
      showTimeAgo: true
      sortDefaultDirection: asc
      sortDefaultKey: structure
      structureUid: 81238b71-adc1-4b01-9efa-6d9e0a71939d
      templateEmail: null
      templateFolderOverride: null
      useQueueForNotifications: false
      users: null
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  redactor-custom-styles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor-split:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor-tweaks:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: cataldo
  schemaVersion: 3.7.33
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
